### ISSUE TITLE
Question: Used direct link instead of <p:link> ?

### ISSUE THREAD

**Issue by Quix0r** [primefaces/showcase#37]
https://github.com/primefaces/showcase/blob/24cfcd9946d24010ca14539e105722b6fce4b34b/src/main/webapp/WEB-INF/template.xhtml#L55

Here, a direct `<a>` tag is being used for generating links. As I know, you should use `<h|p:link>` which is controlled by the JSF engine.

**Comment by tandraschko** [comment]
thats ok - a tag is better for performance and memory for such a simple case ;)

**Comment by Quix0r** [comment]
Or should I go ahead and update it by myself?

**Comment by tandraschko** [comment]
Don't understand you, that "a" is completely ok, there is no need to change it.

**Comment by Quix0r** [comment]
Okay then. I was just curious about it as my trainer told me, to use JSF tags and here (together with navigation roles and cases) it would make sense. :-)

**Comment by tandraschko** [comment]
Everyone has a different opinion ;)
Every component you can EASILY! replace with a simple html tag, means better performance / lower memory usage.

**Comment by tandraschko** [comment]
And, to be honest, i never used navigation rules in my whole live in JSF ;)

**Comment by Quix0r** [comment]
But will that discourage people using PF/JSF at all? I mean, JSF pages are compiled and then cached before being put into service which speeds rendering time a lot up (I did basically the same with one of my older projects, avoiding "expensive" string operations, but it is PHP, not Java).

**Comment by Quix0r** [comment]
Never mind. :-)

**Comment by tandraschko** [comment]
Not really. There is no reason to use JSF components for everything. Otherwise we would end with h:div, h:span, h:legend, ....

Sure, the facelet file is parsed only one time but it's not "compiled" directly. It's not like JSP at all.
Nothing is faster as directly passtrough a string :P

I give you one example:
We developed a big marketplace some years ago and we used h:outputText everywhere.
We used it also just for simple static text, like:
<h:outputText value="Some static text" />

and replaced it with:

Some static text

or 

<span>Some static text</span>


I can't remember how much h:outputText i removed (i'm sure it was above 300 in the whole application) and it speed up our whole benchmark around 10-15%.

**Comment by tandraschko** [comment]
Some old tips from my blog: http://tandraschko.blogspot.de/2012/09/increase-your-jsf-application.html ;)

**Comment by Quix0r** [comment]
Then what are those JSF tags for? E.g. `p:panelGrid` with `columns="x"` (and `layout="grid" for responsiveness) is only counting JSF tags (let's assume `x=3`, then every 3 JSF tags a new row is created, right?), not HTML tags as they are un-managed by the engine, as I know.

**Comment by Quix0r** [comment]
I heard that Amazon and eBay are running on JSF, I don't believe they have to care about weak servers ... ;-)
